analysis.candle-limit=2000
analysis.run-in-loop=true
analysis.pause-seconds=60

clickhouse.url=jdbc:clickhouse://localhost:8123
clickhouse.database=crypto_analyzer
clickhouse.username=cryptoanalyzer
clickhouse.password=cryptoanalyzer123

redis.enabled=true
redis.host=localhost
redis.port=6379
redis.database=0
redis.username=cryptoanalyzer
redis.password=cryptoanalyzer123
redis.key-prefix=market-data
redis.history-max-len=2000

logging.loki.url=http://localhost:3100/loki/api/v1/push
logging.loki.username=
logging.loki.password=
logging.loki.tenant-id=
